import { AlertTriangle, ArrowRight } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import Link from "next/link";

export default function Disclaimer() {
  return (
    <div className="space-y-6 max-w-2xl mx-auto">
      <div className="space-y-2">
        <div className="inline-flex items-center space-x-2">
          <AlertTriangle className="w-6 h-6 text-primary" />
          <h1 className="text-2xl font-bold tracking-tight">Disclaimer</h1>
        </div>
        <p className="text-muted-foreground text-sm">Last updated: January 2024</p>
      </div>

      <Alert variant="destructive" className="border-yellow-600/50 bg-yellow-600/10 text-yellow-600 dark:text-yellow-500">
        <AlertTriangle className="h-4 w-4" />
        <AlertTitle className="text-sm font-medium">Important Notice</AlertTitle>
        <AlertDescription className="mt-2 text-sm">
          <p className="mb-3">
            The demo environment is for preview purposes only. DO NOT use it with real financial data. Always deploy locally for actual use.
          </p>
          <div className="flex flex-wrap gap-2">
            <Link href="https://github.com/adhamafis/curiopay#installation">
              <Button variant="outline" size="sm" className="h-8 text-xs border-yellow-600/50 hover:bg-yellow-600/10">
                View Installation Guide <ArrowRight className="w-3 h-3 ml-1" />
              </Button>
            </Link>
          </div>
        </AlertDescription>
      </Alert>

      <div className="grid gap-3">
        <Card className="bg-card/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">Not Financial Advice</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              CurioPay is a tool for tracking and managing personal finances. The information and insights provided by the application, including those generated by LLM providers, do not constitute financial advice. You should consult with qualified financial professionals for personalized financial advice.
            </p>
          </CardContent>
        </Card>

        <Card className="bg-card/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">No Warranty</h2>
            <div className="space-y-2">
              <p className="text-sm leading-relaxed text-muted-foreground">
                CurioPay is provided on an "as is" and "as available" basis, without any warranties of any kind, either express or implied, including but not limited to:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                <li>Accuracy of financial calculations</li>
                <li>Reliability of AI-generated insights</li>
                <li>Security of local deployments</li>
                <li>Availability of third-party services</li>
                <li>Fitness for any particular purpose</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-muted/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">Limitation of Liability</h2>
            <p className="text-xs leading-relaxed font-mono uppercase text-muted-foreground">
              IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
            </p>
          </CardContent>
        </Card>

        <Card className="bg-card/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">Third-Party Services</h2>
            <div className="space-y-2">
              <p className="text-sm leading-relaxed text-muted-foreground">
                CurioPay integrates with third-party services (LLM providers) but is not affiliated with them. We make no representations regarding these services and are not responsible for:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                <li>Accuracy of AI-generated insights</li>
                <li>Availability of third-party services</li>
                <li>Security of data transmitted to these services</li>
                <li>Changes in their terms, pricing, or functionality</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">User Responsibility</h2>
            <div className="space-y-2">
              <p className="text-sm leading-relaxed text-muted-foreground">
                By using CurioPay, you acknowledge and agree that:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
                <li>You are solely responsible for your financial decisions</li>
                <li>You will maintain appropriate security measures for your deployment</li>
                <li>You will verify any calculations or insights before making financial decisions</li>
                <li>You will comply with all applicable laws and regulations</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card/50">
          <CardContent className="p-4 space-y-2">
            <h2 className="text-lg font-semibold tracking-tight">Open Source Nature</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              As open-source software, CurioPay can be modified and deployed by anyone. We are not responsible for any modifications made by third parties or issues arising from custom deployments.
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="flex justify-center pt-4">
        <Link href="/">
          <Button size="sm" className="bg-primary hover:bg-primary/90">
            Return to Main Page <ArrowRight className="w-3 h-3 ml-1" />
          </Button>
        </Link>
      </div>
    </div>
  );
} 